name: "Build"
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30

    - name: build
      run: nix develop .#build -c buildAll
