name: "update"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30

    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: jellyfin
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: update
      run: ./update.sh --commit

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: updates
        delete-branch: true
        title: '[CI] Package updates'
        draft: false
